#
# Copyright (C) 2020 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



bin-y := gcovered


gcovered-y := main.o opt.o covdata.o statistics.o gcov/ rc/ util/


$(loc_build_tree)/opt.o: $(build_tree)/rc/parser.tab.c

