#
# Copyright (C) 2020 Jan Nowotsch
# Author Jan Nowotsch	<jan.nowotsch@gmail.com>
#
# Released under the terms of the GNU GPL v2.0
#



bin-y := gcovered


gcovered-y := main.o covdata.o file.o gcov/

$(loc_build_tree)/main.o: $(build_tree)/gcov/parser.tab.c
